spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
        url: jdbc:mysql://localhost:3306/qqbot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&useAffectedRows=true
        username: root
        password: 2825097536
  # redis 配置
  redis:
    # 地址
    #host: 192.168.240.1
    host: 110.42.240.230
    #端口，默认为6379
    port: 6380
    # 数据库索引
    database: 1
    # 密码
    #password: Rsxhr4662.
    # 连接超时时间
    timeout: 10s
    password: 2825097536lb
logging:
  level:
    cn.jiegeng.luobin.mapper: debug


mybatis:
  # 搜索指定包别名
  typeAliasesPackage: cn.jiegeng.luobin.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

bot:
 version: v1.9.0
 account: 1786627690
 pwd: 2825097536lb
masterId: 2825097536

sessionToken: eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..HfTm6AzDCfE2oXKq.q1yDdkJ7KUOLFpkvGxoN3wqL22H5SYNsSrJWIAk3cjaoHLdBfgubTs5fuAi2uk3P5whEPZdz2DSDbCgScPhaS_y9WeQPFMc7sPXB9eQiPO0KTb29n9Tsmyfa7NC8PiEoQwMlGojmO-1TkAFSYbHUpwe7lpdHkiAzI-f4iYH2n3GAcsSfa9qe3FYtsaF4lDngTTE7CmpIB48TRpH5LkFKKuFuqNcMmC4A9tmv6Yf8VWlM4ECJc3uLoTnusN36TmWvs3kKmjXR4kewBjZJ6j4T3ZrEk83LBcKpjdB-9cUyOG6mhUtToSeon_1icp3ADn7s7beIZZuaCYB8OcBWjW9VQt4mYDK0wZIFUpW0zGeKUpnz6Iu-UhN1gOEppzhUNEYvjpQ6SldW_42nrfpa7buxBAcTZWDpFK0SO0oIKuPY9XazowlUknyKINKoownKA0BL23NwFKn5c3P5fjLsBveanyEb6iARcf9QE8IV_2Tlvn0oDGHEHblX4hxFtcSgATQghdAFeEmHykcdG-07OjFlYeqZ0RpW0REuLmrURRXVVTsO6HoReWp_0hpTr63fI_U9Dlmfp4YLVieGIvMKvh0PiA-QpT3A_Gi3HZ7fkMLmLgolug5GZW2utBuDOjSnisrXUJwxKtlqyVj3qIrDI4MEbI8emw6KN6fWz_V9tyN5Um7cN2IcGYINx8BHBReofbVRIHITKKujSfGjr8TIJLNS_VT291BkkVC2Cu1oVgRPI_sxRdftl5a6KnGaKqXkoLXKN3eYcpiWjzoQY4IJnytyVBT85_SFpLYGpHUnhKSolOP7xMEgi7lMTru5wwNTik_ipXMTBDMFO1EdHzvZkChijGNAK1HHef8_ML3pgA6EQEzoeozZ1mxCVtmlRiGuJSb5aiHeE2KPXWlLjbL02mYx1gGeSTtIoFlotmOM-ZHf8b9u6iErQVcd5Fke_osobZgV8btSJ2z-3POsRcoc-iygsI--Lea1682BcxD_M5PkatXBeBy6SFEsZf4o2o28zvV5RfkYWd0PmLh22GfIDTkb6m_4Sh54mPdgzfQHIUsI54jcJN9tgvJOEepoEtVRxVE9VUoG8XQoiENRdr2Glhu3jgZhFfRbxavw0_wHSKYw-di8nkbkTfobpP3-oWf6WMOlEcAddmQjV1mG6lxDopaWsnIndd1FvpcAdcYIcfELjj3Hae5W030B64_IwGjg97LSdetR3VRTvAD-DUidJm-WXh9tGHqeuEm42B1opI8-sesSW9f45_HW80RHisIm8QAri1CDu3vxZKLGQUZ9KyrVR5G41KQZ6OTli2nq88eMTnC2AfgNtnxA9AL75mZZt5UAsJCei1H2QqyzJ7aeXmQ-ZGSbo4jSVboAY7FgnMEdgjKxcTzqSjwgwr8hhy68o0PiibrBxLOwU9C2Cn5lVNirokyql04ASXYd7FoBBiDn6cCkoFjMM98FtcGr4jtuWJ-NLwbK1rbk-gejcZlq_cOwwtfJf3cU0pxr9-qPsbeQqiutZX8pupQ2YL0LctdoLeM9scNPnPk5lu9KxwoevRiBxkE1vDUoPRW4QWBgbqRRtAOfCzliVFrMJO7RELppcMUa_AGHjQze3hD9Oxn9_UK8pKdv2sVLA33d7CJIOsnyoz756mvrE6A-TyTeFnrNhC_4hI5uTFWsK2ofW8Z6pl4JoDe1TERd7HUuVa0QzFw2LC28fBQxUzoel0YEgAa_7-AIRv4f6HoRooJH2pQy2sJgzZ6lTw2Z2-wDASkxEODRyEZmssbN595WyWic5bxXb-p-0EFrPcWDt8QmJiWor3BptBA97QmZmD_vYETOHILOd6a4eKzJxmizaT8Rr6OdTu5oYbyre9oP5Hvm5OT1wYPsg01ktleQFN-vfwhOLjZ3unzkus-L-uSDlXuGMEUkfbAtfl4E9310kDO7Lj-ALk4zDTbRF9ypGZJ0rvXUqX9v2K0XNGERaDnfND-IMN9D9dokGEJNGBvRLJXRhrgQtVzkZgFUR_lLftags2lrUhFjfKHEV63GhFTHix_D_PVYk7WGhLy0B3sj34Qbkbuj1hwvqVgrLFIuE7hD8Pqe4dJEBh3ItpG2eB86xGIUIilFZwWoXWJ5UCpb-UkpitCF7Zwk6GYxMyB8R1U79RYGZgsvVQjybrfjBa6LDYdAB_OzoVHiiUKf_uLvNrhEAEhTDjba4dHbxp55-e2gfBiGi5XMbS2UTZbMgVrINeG1fTX9vEfKGOIE6iQ.aaKYrWWq8acYvzzk4Jf2NA
qq: 1786627690
password: 2825097536lb
